// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRUjuudS6ScLGIxB5CUjGJOlR602T9tUQ',
    appId: '1:432775476630:web:bcb23519c739dfb29259b7',
    messagingSenderId: '432775476630',
    projectId: 'labs-3a37a',
    authDomain: 'labs-3a37a.firebaseapp.com',
    storageBucket: 'labs-3a37a.firebasestorage.app',
    measurementId: 'G-SPBJCZXLD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbgVi_knD7KgS8cJFA2SZveNxkM5X_hjQ',
    appId: '1:432775476630:android:b2ba168677dc7a659259b7',
    messagingSenderId: '432775476630',
    projectId: 'labs-3a37a',
    storageBucket: 'labs-3a37a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp2gk67HdAj0BdLzvrM6x7LRYXarQkZow',
    appId: '1:432775476630:ios:aba7cfaf21c4a03b9259b7',
    messagingSenderId: '432775476630',
    projectId: 'labs-3a37a',
    storageBucket: 'labs-3a37a.firebasestorage.app',
    androidClientId: '432775476630-u3qk6tahhp4vrdj4rek94s48vt887af9.apps.googleusercontent.com',
    iosClientId: '432775476630-botuf5lboc3d79rv7bg944hbgcks8es3.apps.googleusercontent.com',
    iosBundleId: 'com.k1r1eiiika.vladslemnev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp2gk67HdAj0BdLzvrM6x7LRYXarQkZow',
    appId: '1:432775476630:ios:b402978b2f9f4ac49259b7',
    messagingSenderId: '432775476630',
    projectId: 'labs-3a37a',
    storageBucket: 'labs-3a37a.firebasestorage.app',
    androidClientId: '432775476630-u3qk6tahhp4vrdj4rek94s48vt887af9.apps.googleusercontent.com',
    iosClientId: '432775476630-okhtpnqqo51u2ceq5ids17kclpblkm3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.labs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRUjuudS6ScLGIxB5CUjGJOlR602T9tUQ',
    appId: '1:432775476630:web:012d67c3cf865ea29259b7',
    messagingSenderId: '432775476630',
    projectId: 'labs-3a37a',
    authDomain: 'labs-3a37a.firebaseapp.com',
    storageBucket: 'labs-3a37a.firebasestorage.app',
    measurementId: 'G-HX73DD5424',
  );
}
